version: 2

registries:
      npm:
        type: npm-registry
        url: https://registry.npmjs.org
        token: ${{secrets.NPM_RC_TOKEN}}
updates:

  # Maintain dependencies for appLogsBigQueryWriter
  - package-ecosystem: "npm"
    registries: 
      - 'npm'
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "nraj-willow"
    pull-request-branch-name:
      separator: "-"
    target-branch: "staging"
    open-pull-requests-limit: 5
